# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder

# Set working directory
WORKDIR /usr/src/app

# Copy package files and install dependencies (including devDependencies) for building
COPY package*.json ./
RUN npm install

# Copy the rest of the source code and build the project
COPY . .
RUN npm run build

# Use a minimal image for the final stage
FROM node:lts-alpine
WORKDIR /usr/src/app

# Copy built files and node_modules from builder
COPY --from=builder /usr/src/app ./

# Remove dev dependencies
RUN npm prune --production

# Command to run the MCP server
CMD ["node", "cli.js"]
