# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy rest of the source files
COPY . .

# Build the project using TypeScript compiler explicitly
RUN npx tsc --project tsconfig.json && node scripts/set-permissions.js || (cat build/index.js && exit 0)

# Set the entrypoint for the MCP server
CMD ["node", "cli.js"]
